services:
  postgres:
    image: postgres:15
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    hostname: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

  django:
    hostname: django
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  pg-data:
