services:
  postgres:
    image: postgres:15
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - ele_network

  adminer:
    image: adminer
    hostname: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - ele_network

  django-prod:
    hostname: django
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    profiles:
      - prod
    networks:
      - ele_network

  django-dev:
    hostname: django
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command:
      - ./manage.py
      - runserver
      - 0.0.0.0:8000
    profiles:
      - dev
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DJANGO_SUPERUSER_PASSWORD: abcdef
      DJANGO_SUPERUSER_USERNAME: root
    networks:
      - ele_network

volumes:
  pg-data:

networks:
  ele_network:
