version: '3'
# This will be focused on development. Production composition file will be under docker-compose-production.yml
services:
    client:
        container_name: react-client
        build: 
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - "./client-react/app:/home/client-react/app"
            - "/home/client-react/node_modules"
        ports:
            - "4000:3000"
        environment:
            REACT_APP_DEV: 1
        depends_on:
            - server
    
    server:
        container_name: node-server
        build:
            context: ./server
            dockerfile: Dockerfile
        #restart: always
        volumes: 
            - './server/node-server:/home/node-server/'
            - '/home/node-server/node_modules'
        ports:
            - '2000:3000'
        # for confidential configurations
        env_file: .env
        environment:
            NODE_ENV: development
            PORT: 3000
