# build environment
FROM node:10 as builder
RUN mkdir -p /var/lib/client-react
WORKDIR /var/lib/client-react
ENV PATH /var/lib/client-react/node_modules/.bin:$PATH
COPY package.json /var/lib/client-react/
RUN npm install
RUN npm install react-scripts
COPY . /var/lib/client-react
RUN npm run build

# production environment
FROM nginx
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx
COPY --from=builder /var/lib/client-react/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
