name: ELE.com Deploy Steps

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Next.js Build Cache
        uses: actions/cache@v2.1.5
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js Version
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build Next.js Site
        run: |
          npm run build

      - name: Test Next.js Site
        run: |
          npm run test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Website
        run: |
          aws s3 sync out/ s3://equinelungexperts.com/www/

      - name: Invalidate Cloudfront Cache
        run: >
          aws cloudfront create-invalidation
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          --paths "/*"
