name: ELE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Maybe do this instead
  # release:
    # types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build Next.js Site
        run: |
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Website
        run: |
          aws s3 sync out/ s3://equinelungexperts.com/www/
