name: Run Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Next.js Build Cache
        uses: actions/cache@v3.0.3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js Version
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Test Next.js Site
        run: |
          npm run test

      - name: Test Next.js Build
        run: |
          npm run build
